# Generated by Django 5.2.4 on 2025-07-30 14:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_on_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='pr_color',
            field=models.CharField(default='Black', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='pr_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='pr_item_type',
            field=models.CharField(choices=[('jeans', 'Jeans'), ('pants', 'Pants'), ('shirts', 'Shirts'), ('t-shirts', 'T-Shirts'), ('suits', 'Suits'), ('frocks', 'Frocks'), ('dresses', 'Dresses'), ('caps', 'Caps'), ('hats', 'Hats'), ('jackets', 'Jackets'), ('sweaters', 'Sweaters'), ('shorts', 'Shorts'), ('skirts', 'Skirts'), ('blouses', 'Blouses'), ('hoodies', 'Hoodies'), ('blazers', 'Blazers'), ('coats', 'Coats'), ('accessories', 'Accessories')], default='shirts', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='pr_size',
            field=models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Double Extra Large'), ('XXXL', 'Triple Extra Large')], default='M', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
